[gpio_instance_6]
ADDRESS = 0x5F938c00

[gpio_own_6]
PIN_1 = "Own"
PIN_5 = "Own"
PIN_7 = "Own"
PIN_8 = "Own"

[gpio_secure_6]
PIN_1 = "Secure"
PIN_5 = "Secure"
PIN_7 = "Secure"
PIN_8 = "Secure"

# P7.n CTRLSEL = (6*14)+n
[gpio_pin_ctrlsel_85]
CTRLSEL = 3

[gpio_pin_ctrlsel_89]
CTRLSEL = 3

[gpio_pin_ctrlsel_91]
CTRLSEL = 3

[gpio_pin_ctrlsel_92]
CTRLSEL = 3